import { DEVICE, RESIZE_ENUM } from './enum';

export const CONST_DATA = {
  DESKTOP: DEVICE.DESKTOP,
  MOBILE: DEVICE.MOBILE,
  DOMAIN_GOOGLE_DOCS: 'docs.google.com',
  POWERED_BY_IMAGE: 'https://w.ladicdn.com/source/v3/by/ladipage.svg',
  STATIC_W_DOMAIN: 'w.ladicdn.com',
  STATIC_S_DOMAIN: 's.ladicdn.com',
  APP_RUNTIME_PREFIX: '_runtime',
  ACTION_TYPE: {
    action: 'action',
    '1st_click': '1st_click',
    '2nd_click': '2nd_click',
    hover: 'hover',
    complete: 'complete',
  },
  DATA_ACTION_TYPE: {
    link: 'link',
    section: 'section',
    email: 'email',
    phone: 'phone',
    popup: 'popup',
    dropbox: 'dropbox',
    hidden_show: 'hidden_show',
    collapse: 'collapse',
    set_value: 'set_value',
    copy_clipboard: 'copy_clipboard',
    change_index: 'change_index',
    set_style: 'set_style',
    set_value_2nd: 'set_value_2nd',
    lightbox: 'lightbox',
    popup_cart: 'popup_cart',
    popup_checkout: 'popup_checkout',
  },
  DATA_ACTION_LIGHTBOX_TYPE: {
    image: 'image',
    video: 'video',
    iframe: 'iframe',
  },
  COUNTDOWN_TYPE: {
    countdown: 'countdown',
    daily: 'daily',
    endtime: 'endtime',
  },
  COUNTDOWN_ITEM_TYPE: {
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    seconds: 'seconds',
  },
  VIDEO_TYPE: { youtube: 'youtube', direct: 'direct' },
  BACKGROUND_STYLE: {
    solid: 'solid',
    gradient: 'gradient',
    image: 'image',
    video: 'video',
  },
  PUBLISH_PLATFORM: {
    ladipage: 'LADIPAGE',
    ladipagedns: 'LADIPAGEDNS',
    wordpress: 'WORDPRESS',
    haravan: 'HARAVAN',
    sapo: 'SAPO',
    shopify: 'SHOPIFY',
    itop: 'ITOPWEBSITE',
    ftp: 'FTP',
    other: 'OTHER',
  },
  SECTION_TYPE: { default: 'DEFAULT', global: 'GLOBAL' },
  TRACKING_NAME: 'ladicid',
  ACCESS_KEY_NAME: 'ladiack',
  REF_NAME: 'ref',
  OTP_TYPE: {
    send: 'OTP_SEND',
    resend: 'OTP_RESEND',
    sms: 'OTP_SMS',
    voice: 'OTP_VOICE',
    zns: 'OTP_ZNS',
  },
  STATUS_SEND: { capture: 1, otp: 1, sendform: 2 },
  PUBLISH_STYLE: { desktop_min_width: 768, mobile_small_min_width: 320 },
  ANIMATED_LIST: [
    'rotate-1',
    'rotate-2',
    'rotate-3',
    'type',
    'scale',
    'loading-bar',
    'slide',
    'clip',
    'zoom',
    'push',
  ],
  POSITION_TYPE: {
    default: 'default',
    top: 'top',
    bottom: 'bottom',
    top_left: 'top_left',
    top_center: 'top_center',
    top_right: 'top_right',
    center_left: 'center_left',
    center_right: 'center_right',
    bottom_left: 'bottom_left',
    bottom_center: 'bottom_center',
    bottom_right: 'bottom_right',
  },
  COLLECTION_TYPE: { carousel: 'carousel', readmore: 'readmore' },
  INPUT_TYPE: {
    tel: 'tel',
    password: 'password',
    text: 'text',
    date: 'date',
    select_multiple: 'select_multiple',
    number: 'number',
    email: 'email',
    textarea: 'textarea',
    select: 'select',
    radio: 'radio',
    checkbox: 'checkbox',
    file: 'file',
    product_variant: 'product_variant',
  },
  CONTENT_TYPE: {
    form_data: 'FORM_DATA',
    form_urlencoded: 'X_WWW_FORM_URLENCODED',
    json: 'JSON',
  },
  SORT_BY_TYPE: { asc: 'asc', desc: 'desc' },
  PRODUCT_VARIANT_TYPE: {
    combined: 'combined',
    combobox: 'combobox',
    label: 'label',
  },
  PRODUCT_VARIANT_OPTION_TYPE: { color: 1, image: 2 },
  PRODUCT_VARIANT_TITLE: { left: 'left', top: 'top' },
  FORM_THANKYOU_TYPE: { default: 'default', url: 'url', popup: 'popup' },
  GAME_RESULT_TYPE: { default: 'default', popup: 'popup' },
  PERCENT_TRACKING_SCROLL: [0, 25, 50, 75, 100],
  TIME_ONPAGE_TRACKING: [10, 30, 60, 120, 180, 300, 600],
  FORM_CONFIG_TYPE: {
    email: 'EMAIL',
    mail_chimp: 'MAIL_CHIMP',
    infusion_soft: 'INFUSION_SOFT',
    infusion_soft_ladi: 'INFUSION_SOFT_LADI',
    active_campaign: 'ACTIVE_CAMPAIGN',
    sendgrid: 'SENDGRID',
    hubspot: 'HUBSPOT',
    smtp: 'SMTP',
    esms: 'ESMS',
    get_response: 'GET_RESPONSE',
    convertkit: 'CONVERTKIT',
    ladiflow: 'LADIFLOW',
    telegram: 'TELEGRAM',
    slack: 'SLACK',
    zalo_zns: 'ZALO_ZNS',
    mautic: 'MAUTIC',
    google_sheet: 'GOOGLE_SHEET',
    google_form: 'GOOGLE_FORM',
    custom_api: 'CUSTOM_API',
    ladisales: 'LADISALES',
    haravan: 'HARAVAN',
    sapo: 'SAPO',
    shopify: 'SHOPIFY',
    nhanh_vn: 'NHANH_VN',
    google_recaptcha: 'GOOGLE_RECAPTCHA',
    google_recaptcha_checkbox: 'GOOGLE_RECAPTCHA_CHECKBOX',
    google_recaptcha_enterprise: 'GOOGLE_RECAPTCHA_ENTERPRISE',
    kiotviet: 'KIOTVIET',
    wordpress: 'WORDPRESS',
    metu: 'METU',
    ladichat: 'LADICHAT',
    shopping: 'SHOPPING',
    blog: 'BLOG',
    conversion_api: 'CONVERSION_API',
    popupx: 'POPUPX',
  },
  FORM_UPLOAD_FILE_LENGTH: 20,
  FORM_UPLOAD_FILE_SIZE: 25,
  CART_LAYOUT: { editable: 'editable', viewonly: 'viewonly' },
  WIDTH_SECTION_RESIZE: {
    [DEVICE.DESKTOP]: 1440,
    [DEVICE.MOBILE]: 768,
  },
  RESIZE_ADD_PIXEL: 300,
  RESIZE_ADD_PIXEL_THUMB: 50,
  RESIZE_RANGE: 50,
  TOOLTIP_TYPE: {
    default: 'default',
    info: 'info',
    success: 'success',
    error: 'error',
    notice: 'notice',
  },
  TOOLTIP_POSITION: {
    top_left: 'top_left',
    top_middle: 'top_middle',
    top_right: 'top_right',
    bottom_left: 'bottom_left',
    bottom_middle: 'bottom_middle',
    bottom_right: 'bottom_right',
    left_top: 'left_top',
    left_middle: 'left_middle',
    left_bottom: 'left_bottom',
    right_top: 'right_top',
    right_middle: 'right_middle',
    right_bottom: 'right_bottom',
  },
  TOOLTIP_SIZE: { small: 'small', medium: 'medium', big: 'big' },
  STORY_PAGE: {
    horizontal: 'horizontal',
    vertical: 'vertical',
    none: 'none',
  },
  COMBOBOX_TYPE: { delivery_method: 'delivery_method' },
  PRODUCT_TYPE: { event: 'Event', service: 'Service', physical: 'Physical' },
};

export const ELEMENT_ID = {
  builder_container_class: 'builder-container',
  builder_editor_id: 'builder-editor',
  builder_container_id: 'builder-container',
  builder_preview_id: 'builder-preview',
  builder_rotate_doc_id: 'builder-rotate-doc',
  builder_mouse_hold_id: 'builder-mouse-hold',
  builder_group_tmp_id: 'builder-group-tmp',
  builder_attribute_editor_id: 'builder-attribute-editor',
  builder_body_editor_id: 'builder-body-editor',
  builder_one_setting_editor_id: 'builder-one-setting-editor',
  builder_quick_editor_id: 'builder-quick-editor',
  builder_section_editor_id: 'builder-section-editor',
  builder_color_editor_id: 'builder-color-editor',
  builder_emoji_id: 'builder-emoji',
  builder_quick_editor_up_down_id: 'builder-quick-editor-up-down',
  builder_quick_editor_move_id: 'builder-quick-editor-move',
  builder_editor_html_id: 'builder-editor-html',
  builder_input_multiple_file_id: 'builder-input-multiple-file',
  builder_input_file_group_new_id: 'builder-input-file-group-new',
  builder_input_your_template_group_new_id:
    'builder-input-your-template-group-new',
  builder_rotate_text_id: 'builder-rotate-text',
  builder_content_tab_page_setting_id: 'builder-content-tab-page-setting',
  builder_content_tab_page_setting_before_head_id:
    'builder-content-tab-page-setting-before-head',
  builder_content_tab_page_setting_before_body_id:
    'builder-content-tab-page-setting-before-body',
  builder_attribute_event_custom_script_id:
    'builder-attribute-event-custom-script',
  builder_type_color_editor_id: 'builder-type-color-editor',
  builder_type_color_gradient_editor_1_id:
    'builder-type-color-gradient-editor-1',
  builder_type_color_gradient_editor_2_id:
    'builder-type-color-gradient-editor-2',
  builder_color_angel_input_id: 'builder-color-angel-input',
  builder_input_section_name_new_id: 'builder-input-section-name-new',
  builder_input_popup_name_new_id: 'builder-input-popup-name-new',
  builder_input_dropbox_name_new_id: 'builder-input-dropbox-name-new',
  builder_input_assets_name_new_id: 'builder-input-assets-name-new',
  builder_input_template_thumb_new_id: 'builder-input-template-thumb-new',
  builder_input_template_thumb_new_name_id:
    'builder-input-template-thumb-new-name',
  builder_input_your_template_item_name_new_id:
    'builder-input-your-template-item-name-new',
  builder_input_file_name_new_id: 'builder-input-file-name-new',
  builder_input_dataset_name_new_id: 'builder-input-dataset-name-new',
  builder_input_link_text_id: 'builder-input-link-text',
  builder_link_editor_id: 'builder-link-editor',
  builder_animated_editor_id: 'builder-animated-editor',
  builder_animated_list_text_id: 'builder-animated-list-text',
  builder_search_file_input_id: 'builder-search-file-input',
  builder_search_shape_input_id: 'builder-search-shape-input',
  builder_quick_editor_input_font_size: 'builder-quick-editor-input-font-size',
  builder_quick_editor_input_border_width:
    'builder-quick-editor-input-border-width',
  builder_quick_editor_input_border_radius:
    'builder-quick-editor-input-border-radius',
  builder_section_tab_id: 'builder-section-tab',
  builder_popup_tab_id: 'builder-popup-tab',
  builder_dropbox_tab_id: 'builder-dropbox-tab',
  builder_banner_tab_id: 'builder-banner-tab',
  builder_file_tab_id: 'builder-file-tab',
  builder_select_form_setting_event_custom_id:
    'builder-select-form-setting-event-custom',
  builder_modal_publish_id: 'builder-modal-publish',
  builder_attribute_action_funnel_id: 'builder-attribute-action-funnel',
  builder_attribute_action_collapse_is_show_id:
    'builder-attribute-action-collapse-is-show',
  builder_input_dataset_search_id: 'builder-input-dataset-search-id',
  builder_input_toggle_grid_id: 'input-toggle-grid',
  builder_input_toggle_snap_id: 'input-toggle-snap',
  builder_input_toggle_swap_element_id: 'input-toggle-swap-element',
  builder_input_toggle_shortcut_all_element_id:
    'input-toggle-shortcut-all-element',
  builder_snap_grid_id: 'builder-snap-grid',
  builder_snap_top_id: 'builder-snap-top',
  builder_snap_left_id: 'builder-snap-left',
  builder_snap_bottom_id: 'builder-snap-bottom',
  builder_snap_right_id: 'builder-snap-right',
  builder_section_popup_id: 'SECTION_POPUP',
  builder_section_background_id: 'BODY_BACKGROUND',
};

export const LADI_RESIZE_TYPE: RESIZE_ENUM[] = [
  RESIZE_ENUM.LADI_N_RESIZE,
  RESIZE_ENUM.LADI_S_RESIZE,
  RESIZE_ENUM.LADI_W_RESIZE,
  RESIZE_ENUM.LADI_E_RESIZE,
  RESIZE_ENUM.LADI_NE_RESIZE,
  RESIZE_ENUM.LADI_NW_RESIZE,
  RESIZE_ENUM.LADI_SE_RESIZE,
  RESIZE_ENUM.LADI_SW_RESIZE,
  // 'ladi-n-resize',
  // 'ladi-s-resize',
  // 'ladi-w-resize',
  // 'ladi-e-resize',
  // 'ladi-ne-resize',
  // 'ladi-nw-resize',
  // 'ladi-se-resize',
  // 'ladi-sw-resize',
];
