import { Injectable } from '@angular/core';
import { DEVICE, ELEMENT_ITEM } from '@constants/enum';
import { IElement } from '@models/element.model';
import {
  getElement,
  getLeftElement,
  getPaddingDevice,
  getTopElement,
  parseFloatLadiPage,
} from '@shares/utility';
import { IDevice } from '@states/menu';
import { IElementObj, IListItemInSnap } from '@states/source';
import { IData, IRuntime } from './runtime.model';

@Injectable({
  providedIn: 'root',
})
export class StateComponentService {
  const = {
    WIDTH_SNAP: 0.5,
    VERSION: 2,
    // LINK_STATIC_DEFAULT: LadiPageConfig.link_static_default,
    // LINK_BUILDER_IMG: LadiPageConfig.link_builder_img,
    VERTICAL: 'vertical',
    HORIZONTAL: 'horizontal',
    LIST_ID_EXCEPT: [
      'SECTION_POPUP',
      'BODY_BACKGROUND',
      'POPUP_CART',
      'POPUP_CHECKOUT',
      'POPUP_PRODUCT',
      'POPUP_BLOG',
      'POPUP_OTP',
      'FORM_OTP_DEFAULT',
      'default',
    ],
    ELEMENT_START_PREFIX: [
      'DROPBOX',
      'QUANTITY',
      'VARIANT',
      'BUTTON_ADD_TO_CART',
      'BUTTON_BUY_NOW',
      'CART_BUTTON',
      'FORM_LOGIN',
      'FORM_OTP',
      'PEN_TOOL',
      'PRODUCT_LIST',
      'CART_ICON',
      'TAB_ITEM',
      'ACCORDION_MENU',
      'ACCORDION_SHAPE',
      'ACCORDION_CONTENT',
    ],
    GOOGLE_RECAPTCHA_CHECKBOX_POSITION: {
      left: 'left',
      center: 'center',
      right: 'right',
    },
    BACKGROUND_STYLE_FULL: { width: 'width', height: 'height' },
    GRADIENT_TYPE: {
      linear_prefix: 'linear-gradient',
      linear: 'linear-gradient({0}deg, {1}, {2})',
      radial_prefix: 'radial-gradient',
      radial: 'radial-gradient(circle, {0}, {1})',
    },
    ARROW_TYPE: { none: 'none', default: 'default', custom: 'custom' },
    TARGET_LINK: { self: '_self', blank: '_blank' },
    FILE_ACCEPT_TYPE: {
      image: '.jpg, .jpeg, .png, .gif, .svg, .ico',
      video: '.mp4',
      font: '.ttf, .otf, .woff2',
      document: '.txt, .doc, .docx, .xls, .xlsx, .pdf',
      audio: '.mp3',
    },
    EDITOR_TYPE: {
      datetime: 'datetime',
      time: 'time',
      list_tab: 'list_tab',
      list_frame: 'list_frame',
      list_section_tab: 'list_section_tab',
      shape_html: 'shape_html',
      shape_html_2nd_click: 'shape_html_2nd_click',
      banner_resize: 'banner_resize',
      constraint: 'constraint',
      animation: 'animation',
      countdown_item_margin_right: 'countdown_item_margin_right',
      icon_image: 'icon_image',
      text_shadow: 'text_shadow',
      edit_text_font1: 'edit_text_font1',
      edit_text_font2: 'edit_text_font2',
      edit_shape_align: 'edit_shape_align',
      background_image: 'background_image',
      backdrop_image: 'backdrop_image',
      overlay_image: 'overlay_image',
      filter: 'filter',
      transform: 'transform',
      box_shadow: 'box_shadow',
      icon_setting_preview: 'icon_setting_preview',
      color: 'color',
      color_gradient: 'color_gradient',
      color_gradient_1: 'color_gradient_1',
      color_gradient_2: 'color_gradient_2',
      seconds: 'seconds',
      gallery_item: 'gallery_item',
      survey_option: 'survey_option',
      array_line: 'array_line',
      array_space: 'array_space',
      object: 'object',
      deg: 'deg',
      text: 'text',
      dataset: 'dataset',
      textarea: 'textarea',
      image: 'image',
      image_2nd_click: 'image_2nd_click',
      shape: 'shape',
      script: 'script',
      action: 'action',
      data_event: 'data_event',
      data_event_item: 'data_event_item',
      checkbox1: 'checkbox1',
      number: 'number',
      pixel: 'pixel',
      mask: 'mask',
      option: 'option',
      boolean: 'boolean',
      multiple_option: 'multiple_option',
      table_width_header: 'table_width_header',
    },
    ELEMENT_CHILD_ALIGN: {
      left: 'left',
      right: 'right',
      top: 'top',
      bottom: 'bottom',
      center_vertical: 'center_vertical',
      center_horizontal: 'center_horizontal',
      distribute_vertical: 'distribute_vertical',
      distribute_horizontal: 'distribute_horizontal',
      auto: 'auto',
    },
    ELEMENT_EVENT: { selected: 'selected', hold: 'hold' },
    ROLLBACK_ACTION_TYPE: {
      add: 'add',
      delete: 'delete',
      update_old: 'update_old',
      update_new: 'update_new',
    },
    RESIZE_RULE: {
      n: 'n',
      e: 'e',
      w: 'w',
      s: 's',
      ne: 'ne',
      nw: 'nw',
      se: 'se',
      sw: 'sw',
    },
    TYPE_FILE: {
      video: 'VIDEO',
      image: 'IMAGE',
      font: 'FONT',
      document: 'DOCUMENT',
      audio: 'AUDIO',
      section: 'section',
      popup: 'popup',
      dropbox: 'dropbox',
      assets: 'assets',
      banner: 'banner',
    },
    LADIPAGE_LIST_TYPE: {
      ladipage: 'LADIPAGE',
      popupx: 'POPUPX',
      popupx_popup: 'POPUPX_POPUP',
      popupx_sticky_bar: 'POPUPX_STICKY_BAR',
    },
    REPEATER_TYPE: {
      image_src: 'image_src',
      gallery_images: 'gallery_images',
      shape_html: 'shape_html',
      video_value: 'video_value',
      video_type: 'video_type',
      sub_group_setting_background: 'setting_background',
      group_design: 'design',
      group_effect: 'effect',
    },
    MEDIA_MANAGER_TYPE: {
      video: 'video',
      ladipage: 'ladipage',
      unsplash: 'UNSPLASH',
      pixabay: 'PIXABAY',
      pexels: 'PEXELS',
      illustration: 'Illustration',
      free: 'FREE',
    },
    PACKAGE_TYPE: { premium: 'PREMIUM', free: 'FREE' },
    SURVEY_TYPE: { text: 'text', image: 'image', text_image: 'text_image' },
    SETTING_INTEGRATIONS_TYPE: {
      form_config: 'form_config',
      form_account: 'form_account',
      tracking: 'tracking',
    },
    FORM_ACCOUNT_GROUP: {
      form_data: 'FORM_DATA',
      publish: 'PUBLISH',
      product: 'PRODUCT',
    },
    ADV_INTEGRATIONS_TYPE: { default: 'default', publish: 'publish' },
    DATASET_FIELD_GROUP_TYPE: { system: 'SYSTEM', primary: 'PRIMARY' },
    TABLE_STICKY_HEADER_TYPE: {
      header: 'header',
      column_1: 'column_1',
      header_column_1: 'header_column_1',
    },
    DESIGN_TYPE: {
      responsive: 'RESPONSIVE',
      adaptive: 'ADAPTIVE',
      mobile_only: 'MOBILE_ONLY',
    },
  };
  runtime: IRuntime = {
    now: Date.now(),
    position_element: {
      desktop: {},
      mobile: {},
    },
    element_is_dragging: false,
    size_element: {},
    size_image_element: {},
    size_image_crop_element: {},
    element_select_parent: !0,
    element_select_parent_first: !0,
    mouse_hold_position_x: 0,
    mouse_hold_position_y: 0,
    max_data_event_length: 10,
    file_upload_max_item: 10,
    form_file_upload_max_item: 5,
    builder_container_class: 'builder-container',
    builder_editor_id: 'builder-editor',
    builder_container_id: 'builder-container',
    builder_preview_id: 'builder-preview',
    builder_rotate_doc_id: 'builder-rotate-doc',
    builder_mouse_hold_id: 'builder-mouse-hold',
    builder_group_tmp_id: 'builder-group-tmp',
    builder_attribute_editor_id: 'builder-attribute-editor',
    builder_body_editor_id: 'builder-body-editor',
    builder_one_setting_editor_id: 'builder-one-setting-editor',
    builder_quick_editor_id: 'builder-quick-editor',
    builder_section_editor_id: 'builder-section-editor',
    builder_color_editor_id: 'builder-color-editor',
    builder_emoji_id: 'builder-emoji',
    builder_quick_editor_up_down_id: 'builder-quick-editor-up-down',
    builder_quick_editor_move_id: 'builder-quick-editor-move',
    builder_editor_html_id: 'builder-editor-html',
    builder_input_multiple_file_id: 'builder-input-multiple-file',
    builder_input_file_group_new_id: 'builder-input-file-group-new',
    builder_input_your_template_group_new_id:
      'builder-input-your-template-group-new',
    builder_rotate_text_id: 'builder-rotate-text',
    builder_content_tab_page_setting_id: 'builder-content-tab-page-setting',
    builder_content_tab_page_setting_before_head_id:
      'builder-content-tab-page-setting-before-head',
    builder_content_tab_page_setting_before_body_id:
      'builder-content-tab-page-setting-before-body',
    builder_attribute_event_custom_script_id:
      'builder-attribute-event-custom-script',
    builder_type_color_editor_id: 'builder-type-color-editor',
    builder_type_color_gradient_editor_1_id:
      'builder-type-color-gradient-editor-1',
    builder_type_color_gradient_editor_2_id:
      'builder-type-color-gradient-editor-2',
    builder_color_angel_input_id: 'builder-color-angel-input',
    builder_input_section_name_new_id: 'builder-input-section-name-new',
    builder_input_popup_name_new_id: 'builder-input-popup-name-new',
    builder_input_dropbox_name_new_id: 'builder-input-dropbox-name-new',
    builder_input_assets_name_new_id: 'builder-input-assets-name-new',
    builder_input_template_thumb_new_id: 'builder-input-template-thumb-new',
    builder_input_template_thumb_new_name_id:
      'builder-input-template-thumb-new-name',
    builder_input_your_template_item_name_new_id:
      'builder-input-your-template-item-name-new',
    builder_input_file_name_new_id: 'builder-input-file-name-new',
    builder_input_dataset_name_new_id: 'builder-input-dataset-name-new',
    builder_input_link_text_id: 'builder-input-link-text',
    builder_link_editor_id: 'builder-link-editor',
    builder_animated_editor_id: 'builder-animated-editor',
    builder_animated_list_text_id: 'builder-animated-list-text',
    builder_search_file_input_id: 'builder-search-file-input',
    builder_search_shape_input_id: 'builder-search-shape-input',
    builder_quick_editor_input_font_size:
      'builder-quick-editor-input-font-size',
    builder_quick_editor_input_border_width:
      'builder-quick-editor-input-border-width',
    builder_quick_editor_input_border_radius:
      'builder-quick-editor-input-border-radius',
    builder_section_tab_id: 'builder-section-tab',
    builder_popup_tab_id: 'builder-popup-tab',
    builder_dropbox_tab_id: 'builder-dropbox-tab',
    builder_banner_tab_id: 'builder-banner-tab',
    builder_file_tab_id: 'builder-file-tab',
    builder_select_form_setting_event_custom_id:
      'builder-select-form-setting-event-custom',
    builder_modal_publish_id: 'builder-modal-publish',
    builder_attribute_action_funnel_id: 'builder-attribute-action-funnel',
    builder_attribute_action_collapse_is_show_id:
      'builder-attribute-action-collapse-is-show',
    builder_input_dataset_search_id: 'builder-input-dataset-search-id',
    builder_input_toggle_grid_id: 'input-toggle-grid',
    builder_input_toggle_snap_id: 'input-toggle-snap',
    builder_input_toggle_swap_element_id: 'input-toggle-swap-element',
    builder_input_toggle_shortcut_all_element_id:
      'input-toggle-shortcut-all-element',
    builder_snap_grid_id: 'builder-snap-grid',
    builder_snap_top_id: 'builder-snap-top',
    builder_snap_left_id: 'builder-snap-left',
    builder_snap_bottom_id: 'builder-snap-bottom',
    builder_snap_right_id: 'builder-snap-right',
    builder_snap_rect: {
      top: 0,
      left: 0,
    },
    builder_attribute_input_move: !1,
    builder_attribute_input_move_min_pixel: 1,
    builder_attribute_input_move_diff_percent: 5,
    builder_attribute_input_move_element: null,
    builder_attribute_input_move_value: 0,
    builder_attribute_input_move_position_x: 0,
    builder_is_hold: !1,
    builder_is_hold_group_tmp: !1,
    builder_is_quick_editor_up_down: !1,
    builder_is_quick_editor_move: !1,
    builder_is_menu_move: !1,
    builder_is_image_background_move: !1,
    builder_is_image_background_resize: !1,
    builder_is_resize: !1,
    builder_is_rotate: !1,
    builder_is_show_type_image_display: !1,
    is_meta_key: !1,
    builder_menu_move_element: null,
    builder_resize_rule: '',
    builder_mapping_attribute: null,
    builder_unique_id: 1,
    builder_pickr_object: {},
    builder_position_click_x: 0,
    builder_position_click_y: 0,
    builder_position_click_double_click_max: 3,
    builder_constraint_size: !0,
    builder_gradient_editor_all: !1,
    builder_max_count_banner_download: 25,
    builder_section_max_height_sticky: 150,
    builder_menu_top: 56,
    builder_menu_left: 0,
    builder_menu_right: 0,
    builder_menu_bottom: 0,
    builder_carousel_crop: {},
    builder_image_crop: {},
    current_event: this.const.ELEMENT_EVENT.selected,
    current_pixel_snap: 0,
    current_element_id: '',
    current_element_type: '',
    current_element_parent_type: null,
    current_element_parent_id: null,
    current_element_hover_id: null,
    current_addnew_section_id: null,
    current_addnew_section_is_last: !1,
    current_addnew_section_callback: null,
    current_margin_top_popup: 0,
    current_popup_id: '',
    check_click_first_child: !0,
    count_mouse_down_click: 0,
    current_select_text_range: null,
    current_scope: {
      [DEVICE.DESKTOP]: {},
      [DEVICE.MOBILE]: {},
    },
    image_crop_check_position: !1,
    image_crop_check_size: !1,
    is_attribute_group_tmp: !0,
    is_alt_key: !1,
    is_shift_key: !1,
    is_ctrl_key: !1,
    is_select_text: !1,
    is_ready: !1,
    is_saved: !0,
    is_preview: !1,
    is_double_click: !1,
    id_element_end_up_down: null,
    is_element_not_move_out: !1,
    is_adaptive_design: !1,
    pixel_element_first_child_click: 2,
    pixel_element_snap_desktop: 5,
    pixel_element_snap_mobile: 3,
    list_option_value_new: {},
    list_tracking_global: null,
    list_domain_free: null,
    list_new_parent_tmp: {},
    list_run_multiple_background: {},
    list_element_up_down: [],
    list_element_in_screen: [],
    list_element_in_screen_no_fixed: [],
    list_section_in_screen: [],
    list_group_your_section: null,
    list_group_your_assets: null,
    list_group_your_popup: null,
    list_group_your_dropbox: null,
    list_group_template_section: null,
    list_group_template_popup: null,
    list_group_template_dropbox: null,
    list_group_template_banner: null,
    list_template_section_item_load_finish: {},
    list_template_popup_item_load_finish: {},
    list_template_assets_item_load_finish: {},
    list_template_dropbox_item_load_finish: {},
    list_template_banner_item_load_finish: {},
    list_template_section_item_page: {},
    list_template_popup_item_page: {},
    list_template_assets_item_page: {},
    list_template_dropbox_item_page: {},
    list_template_banner_item_page: {},
    list_element_in_screen_snap: [],
    list_section_in_screen_snap: [],
    list_element_ctrl: [],
    list_element_group_tmp: [],
    list_group_file: null,
    list_group_document: null,
    list_group_video: null,
    list_group_image: null,
    list_file_page: {},
    list_file_load_finish: {},
    list_file_search_page: {},
    list_file_search_load_finish: {},
    list_shape_api_page: {},
    list_shape_api_load_finish: {},
    list_color_gradient: {},
    list_color_solid: {},
    list_emoji: {},
    list_symbols: {},
    list_emoji_all: [],
    list_edit_history: null,
    tmp: {
      check_mouse_down_builder: false,
    },
    timeout_animation_demo_id: null,
    timenow_mouse_down_click: 0,
    time_double_click: 500,
    time_element_first_child_click: 250,
    timenow_element_click: 0,
    time_element_child_click: 250,
    time_run_background_slowdown: 20,
    scrollbar_size: 4,
    size_image_max_dimension: { width: 3e3, height: 3e3 },
    time_reload_attribute: 300,
    time_reload_sub_tab: {
      design: 10,
      event: 3,
      effect: 3,
      data: 3,
      advance: 3,
    },
    reload_sub_tab_all: !0,
    time_reload_sub_tab_other: 300,
    ui_view_top_menu: 'top-menu',
    ui_view_left_menu: 'left-menu',
    ui_view_right_menu: 'right-menu',
    ui_view_preview_menu: 'preview-menu',
    ui_view_bottom_menu: 'bottom-menu',
    ui_view_attribute_editor: 'attribute-editor',
    ui_view_body_editor: 'body-editor',
    ui_view_one_setting_editor: 'one-setting-editor',
    ui_view_quick_editor: 'quick-editor',
    ui_view_section_editor: 'section-editor',
    ui_view_pen_tool_editor: 'pen-tool-editor',
    is_popup_scroll_height: false,
    backdrop_popup_id: '',
    builder_section_popup_id: '',
    is_builder_banner: false,
    element_editing_id: '',
    // new
    currentElementType: 'noon',
  };
  public data: IData = {
    title: '',
    description: '',
    keyword: '',
    image: '',
    favicon: '',
    is_lazyload: !0,
    is_mobile_only: !1,
    story_page: {
      // type: this.const.STORY_PAGE.none,
      is_autoplay: !1,
      autoplay_time: 10,
    },
    is_follow: !0,
    tracking_global_id: null,
    tracking_global_delay: null,
    facebook_pixel: '',
    tiktok_pixel: '',
    google_analytics_id: '',
    google_ads_id: '',
    google_tag_manager_id: '',
    before_head: '',
    before_body: '',
    font_default: '"Open Sans", sans-serif',
    adv: null,
    adv_publish: {},
    thankyou_page: {},
    is_view_content: !0,
    tracking_button_click: !0,
    shopping: {},
    device_screen: DEVICE.DESKTOP,
    width: {},
    is_snap: !1,
    is_swap_element: !1,
    is_shortcut_all_element: !1,
    snap_grid: { isEnable: !1, range: 10 },
    elements: {},
    tmp: {},
    // version: this.const.VERSION,
    index_element: 0,
    index_element_option: 0,
  };

  addElement(element: any, id: string) {
    this.data.elements[id] = element;
  }

  setPositionElement(id: string, device: IDevice, listElement: IElementObj) {
    const ele = getElement(listElement, id, !1) as IElement;
    if (ele?.id) {
      const padding = getPaddingDevice(id, device);
      const top = getTopElement(id, device.deviceScreen, null),
        left = getLeftElement(id, device.deviceScreen, listElement) + padding,
        width = parseFloatLadiPage(ele[device.deviceScreen]?.style?.width),
        height = parseFloatLadiPage(ele[device.deviceScreen]?.style?.height);
      (this.runtime.position_element as any)[device.deviceScreen][id] = {
        top,
        left,
        width,
        height,
      };
    }
  }

  getElementInSnapValue(
    id: string,
    device: IDevice,
    listElement: IElementObj,
    isGetNew: boolean = false
  ): IListItemInSnap {
    const ele = getElement(listElement, id, !1) as IElement;
    // const padding = getPaddingDevice(id, device);
    const padding = 0;
    const top = getTopElement(
        id,
        device.deviceScreen,
        null,
        isGetNew ? undefined : this.runtime.position_element
      ),
      left = getLeftElement(id, device.deviceScreen, listElement) + padding,
      width = parseFloatLadiPage(ele[device.deviceScreen]?.style?.width),
      height = parseFloatLadiPage(ele[device.deviceScreen]?.style?.height);
    return {
      id,
      width,
      height,
      top,
      left,
      topheight: top + height,
      topheightcenter: top + height / 2,
      leftwidth: left + width,
      leftwidthcenter: left + width / 2,
      element: ele,
    };
  }
}
